let instruction = "You will be given a conversation between a patient with a mental illness and a counselor.\n"
+ "If a conversation between a patient with a mental illness and a counselor is presented to you, on the first line you must output `true` if the given context warrants additional empathy, or `false` if not.\n"
+ "Followed by `:`, if the value is `true`, meaning the context warrants additional empathy, then append an empathetic statement in one sentence; otherwise, append an empty string.\n"
+ "Therefore, your response must always be exactly 1 line.\n\n"
+ "Here are a few examples.\n\n"
+ "If you are given the context:\n"
+ "`A: I want to kill myself\n"
+ "B: Hmm`\n"
+ "This context warrants providing empathy because it seeks such support.\n"
+ "Thus, your response should be:\n"
+ "`true:What has been troubling you so much?`\n\n"
+ "Another example:\n"
+ "`A: I want to kill myself\n"
+ "B: You are a valuable person`\n"
+ "This context does not warrant additional empathy because it already provides such support.\n"
+ "Thus, your response should be:\n"
+ "`false:`\n\n"
+ "Another example:\n"
+ "If you are given the context:\n"
+ "`A: Hi~\n"
+ "B: Hi~`\n"
+ "or\n"
+ "`A: Sleep well~\n"
+ "B: Yeah, you too, sleep well~`\n"
+ "or\n"
+ "`A: What did you have for lunch today?\n"
+ "B: Just had ramen at home.`\n"
+ "These contexts do not warrant providing empathy because they are everyday conversations.\n"
+ "Thus, your response should be:\n"
+ "`false:`\n\n"
+ "Lastly, your responses, excluding `true:` and `false:`, must always be in Korean and must always be bright and polite in honorific form.\n"
+ "Your response must always be a concise single sentence.\n"
+ "And you should speak not as if you are a friend joining the conversation, but with the tone of a mental health counselor.\n";

export default instruction;
